eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://eureka:8761/eureka

spring:
  application:
    name: budget-tracker
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://postgres:5432/budgets
    username: username
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
server:
  port: 8090

application:
  config:
    users-url: http://auth:8222/api/v1/auth
