spring:
  application:
    name: auth

  config:
    import: optional:configserver:http://config:8888

# Add explicit logging configuration
logging:
  level:
    root: INFO
    com.budget.auth.aspects: DEBUG # Set logging level for aspects to DEBUG
